import {
  FileText,
  FileCode,
  FileVideo,
  FileAudio,
  FileSpreadsheet,
  FileArchive,
} from "lucide-react";

// Map other extensions to icons using Map
export const ICON_FILE_TYPE_MAP = new Map<string, typeof FileText>([
  ["pdf", FileText],
  ["doc", FileText],
  ["docx", FileText],
  ["txt", FileText],
  ["rtf", FileText],
  ["md", FileText],
  ["js", FileCode],
  ["jsx", FileCode],
  ["ts", FileCode],
  ["tsx", FileCode],
  ["py", FileCode],
  ["java", FileCode],
  ["cpp", FileCode],
  ["c", FileCode],
  ["html", FileCode],
  ["css", FileCode],
  ["json", FileCode],
  ["xml", FileCode],
  ["yaml", FileCode],
  ["yml", FileCode],
  ["mp4", FileVideo],
  ["avi", FileVideo],
  ["mov", FileVideo],
  ["wmv", FileVideo],
  ["flv", FileVideo],
  ["webm", FileVideo],
  ["mkv", FileVideo],
  ["mp3", FileAudio],
  ["wav", FileAudio],
  ["flac", FileAudio],
  ["aac", FileAudio],
  ["ogg", FileAudio],
  ["m4a", FileAudio],
  ["xls", FileSpreadsheet],
  ["xlsx", FileSpreadsheet],
  ["csv", FileSpreadsheet],
  ["zip", FileArchive],
  ["rar", FileArchive],
  ["7z", FileArchive],
  ["tar", FileArchive],
  ["gz", FileArchive],
]);

// Map file extensions to colors (bg color / icon color) using Map
export const COLOR_FILE_TYPE_MAP = new Map<
  string,
  { bg: string; icon: string }
>([
  ["pdf", { bg: "bg-red-500/15", icon: "text-red-600" }],
  ["doc", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["docx", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["txt", { bg: "bg-gray-500/15", icon: "text-gray-600" }],
  ["rtf", { bg: "bg-gray-500/15", icon: "text-gray-600" }],
  ["md", { bg: "bg-gray-500/15", icon: "text-gray-600" }],
  ["js", { bg: "bg-yellow-500/15", icon: "text-yellow-600" }],
  ["jsx", { bg: "bg-yellow-500/15", icon: "text-yellow-600" }],
  ["ts", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["tsx", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["py", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["java", { bg: "bg-orange-500/15", icon: "text-orange-600" }],
  ["cpp", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["c", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["html", { bg: "bg-orange-500/15", icon: "text-orange-600" }],
  ["css", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["json", { bg: "bg-gray-500/15", icon: "text-gray-600" }],
  ["xml", { bg: "bg-orange-500/15", icon: "text-orange-600" }],
  ["yaml", { bg: "bg-purple-500/15", icon: "text-purple-600" }],
  ["yml", { bg: "bg-purple-500/15", icon: "text-purple-600" }],
  ["mp4", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["avi", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["mov", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["wmv", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["flv", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["webm", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["mkv", { bg: "bg-blue-500/15", icon: "text-blue-600" }],
  ["mp3", { bg: "bg-purple-500/15", icon: "text-purple-600" }],
  ["wav", { bg: "bg-purple-500/15", icon: "text-purple-600" }],
  ["flac", { bg: "bg-purple-500/15", icon: "text-purple-600" }],
  ["aac", { bg: "bg-purple-500/15", icon: "text-purple-600" }],
  ["ogg", { bg: "bg-purple-500/15", icon: "text-purple-600" }],
  ["m4a", { bg: "bg-purple-500/15", icon: "text-purple-600" }],
  ["xls", { bg: "bg-green-500/15", icon: "text-green-600" }],
  ["xlsx", { bg: "bg-green-500/15", icon: "text-green-600" }],
  ["csv", { bg: "bg-green-500/15", icon: "text-green-600" }],
  ["zip", { bg: "bg-amber-500/15", icon: "text-amber-600" }],
  ["rar", { bg: "bg-amber-500/15", icon: "text-amber-600" }],
  ["7z", { bg: "bg-amber-500/15", icon: "text-amber-600" }],
  ["tar", { bg: "bg-amber-500/15", icon: "text-amber-600" }],
  ["gz", { bg: "bg-amber-500/15", icon: "text-amber-600" }],
]);
